subtitle: Data Carpentry for Social Sciences and Humanities
format: 
  revealjs: 
    navigation-mode: vertical
    theme: dc-ldev.scss
    df-print: paged
    self-contained: true
execute: 
  warning: false
  echo: true
  message: false
engine: knitr